fixed_vector: remove template parameter from scalar constructor
The template scalar constructor of fixed_vector<T, N> is problematic,
since it causes ambiguities when converting from boost::assign::list_of
to fixed_vector<T, N>, e.g. T = size_t.

This issue never became apparent since the specialised forms of
fixed_vector<T, N> have a non-template scalar constructor.

test/unit/mdsim/binning.cpp:508:39: error: conversion from 'boost::assign_detail::generic_list<unsigned long>' to
      'test_type::shape_type' (aka 'fixed_vector<size_t, 2>') is ambiguous
                test_type::shape_type shape = list_of(2 * unit)(3 * unit);
                                      ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
boost/assign/list_of.hpp:434:9: note: candidate function [with Container =
      halmd::detail::numeric::blas::fixed_vector<unsigned long, 2>]
        operator Container() const
        ^
halmd/numeric/blas/fixed_vector/size_N.hpp:51:23: note: candidate constructor [with U =
      boost::assign_detail::generic_list<unsigned long>]
    HALMD_GPU_ENABLED fixed_vector(U const& s,
                      ^
test/unit/mdsim/binning.cpp:520:39: error: conversion from 'boost::assign_detail::generic_list<unsigned long>' to
      'test_type::shape_type' (aka 'fixed_vector<size_t, 3>') is ambiguous
                test_type::shape_type shape = list_of(2 * unit)(5 * unit)(3 * unit);
                                      ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
boost/assign/list_of.hpp:434:9: note: candidate function [with Container =
      halmd::detail::numeric::blas::fixed_vector<unsigned long, 3>]
        operator Container() const
        ^
halmd/numeric/blas/fixed_vector/size_N.hpp:51:23: note: candidate constructor [with U =
      boost::assign_detail::generic_list<unsigned long>]
    HALMD_GPU_ENABLED fixed_vector(U const& s,
                      ^