gpu::density_mode: use gpu::samples::phase_space instead of gpu::particle.
GPU to GPU phase space sampling was not implemented as of commit
fee8daf, which is the reason for the prior use of gpu::particle.

This commit removes the (indirect) dependency on gpu::particle.

Note that both the 2d and 3d ssf unit tests now fail:

Entering test case "ssf_gpu_2d"
…
acquire phase space sample
acquire phase space sample
compute density modes
compute static structure factor
halmd/test/unit/observables/ssf.cpp(192): error in "ssf_gpu_2d": absolute value of fabs(result[i][0] - get<1>(ssf_ref[i])) / npart{1} exceeds 1.1920928955078125e-05
halmd/test/unit/observables/ssf.cpp(192): error in "ssf_gpu_2d": absolute value of fabs(result[i][0] - get<1>(ssf_ref[i])) / npart{1} exceeds 1.1920928955078125e-05
halmd/test/unit/observables/ssf.cpp(192): error in "ssf_gpu_2d": absolute value of fabs(result[i][0] - get<1>(ssf_ref[i])) / npart{1} exceeds 1.1920928955078125e-05
halmd/test/unit/observables/ssf.cpp(192): error in "ssf_gpu_2d": absolute value of fabs(result[i][0] - get<1>(ssf_ref[i])) / npart{0.5} exceeds 1.1920928955078125e-05
halmd/test/unit/observables/ssf.cpp(200): error in "ssf_gpu_2d": absolute value of fabs(result[i][1] - S_q_err) / max(S_q_err, 1.){1} exceeds 1.1920928955078125e-05
halmd/test/unit/observables/ssf.cpp(192): error in "ssf_gpu_2d": absolute value of fabs(result[i][0] - get<1>(ssf_ref[i])) / npart{1} exceeds 1.1920928955078125e-05
halmd/test/unit/observables/ssf.cpp(192): error in "ssf_gpu_2d": absolute value of fabs(result[i][0] - get<1>(ssf_ref[i])) / npart{0.5} exceeds 1.1920928955078125e-05
halmd/test/unit/observables/ssf.cpp(200): error in "ssf_gpu_2d": absolute value of fabs(result[i][1] - S_q_err) / max(S_q_err, 1.){1} exceeds 1.1920928955078125e-05
halmd/test/unit/observables/ssf.cpp(192): error in "ssf_gpu_2d": absolute value of fabs(result[i][0] - get<1>(ssf_ref[i])) / npart{0.5} exceeds 1.1920928955078125e-05
halmd/test/unit/observables/ssf.cpp(200): error in "ssf_gpu_2d": absolute value of fabs(result[i][1] - S_q_err) / max(S_q_err, 1.){1} exceeds 1.1920928955078125e-05
Leaving test case "ssf_gpu_2d"; testing time: 2800ms
Entering test case "ssf_gpu_3d"
…
acquire phase space sample
compute density modes
compute static structure factor
halmd/test/unit/observables/ssf.cpp(192): error in "ssf_gpu_3d": absolute value of fabs(result[i][0] - get<1>(ssf_ref[i])) / npart{1} exceeds 1.1920928955078125e-05
halmd/test/unit/observables/ssf.cpp(192): error in "ssf_gpu_3d": absolute value of fabs(result[i][0] - get<1>(ssf_ref[i])) / npart{1} exceeds 1.1920928955078125e-05
halmd/test/unit/observables/ssf.cpp(192): error in "ssf_gpu_3d": absolute value of fabs(result[i][0] - get<1>(ssf_ref[i])) / npart{1} exceeds 1.1920928955078125e-05
halmd/test/unit/observables/ssf.cpp(192): error in "ssf_gpu_3d": absolute value of fabs(result[i][0] - get<1>(ssf_ref[i])) / npart{1} exceeds 1.1920928955078125e-05
halmd/test/unit/observables/ssf.cpp(192): error in "ssf_gpu_3d": absolute value of fabs(result[i][0] - get<1>(ssf_ref[i])) / npart{0.75} exceeds 1.1920928955078125e-05
halmd/test/unit/observables/ssf.cpp(200): error in "ssf_gpu_3d": absolute value of fabs(result[i][1] - S_q_err) / max(S_q_err, 1.){1} exceeds 1.1920928955078125e-05
halmd/test/unit/observables/ssf.cpp(192): error in "ssf_gpu_3d": absolute value of fabs(result[i][0] - get<1>(ssf_ref[i])) / npart{0.5} exceeds 1.1920928955078125e-05
halmd/test/unit/observables/ssf.cpp(200): error in "ssf_gpu_3d": absolute value of fabs(result[i][1] - S_q_err) / max(S_q_err, 1.){1} exceeds 1.1920928955078125e-05
halmd/test/unit/observables/ssf.cpp(192): error in "ssf_gpu_3d": absolute value of fabs(result[i][0] - get<1>(ssf_ref[i])) / npart{1} exceeds 1.1920928955078125e-05
halmd/test/unit/observables/ssf.cpp(192): error in "ssf_gpu_3d": absolute value of fabs(result[i][0] - get<1>(ssf_ref[i])) / npart{1} exceeds 1.1920928955078125e-05
halmd/test/unit/observables/ssf.cpp(192): error in "ssf_gpu_3d": absolute value of fabs(result[i][0] - get<1>(ssf_ref[i])) / npart{0.5} exceeds 1.1920928955078125e-05
halmd/test/unit/observables/ssf.cpp(200): error in "ssf_gpu_3d": absolute value of fabs(result[i][1] - S_q_err) / max(S_q_err, 1.){1} exceeds 1.1920928955078125e-05
halmd/test/unit/observables/ssf.cpp(192): error in "ssf_gpu_3d": absolute value of fabs(result[i][0] - get<1>(ssf_ref[i])) / npart{1} exceeds 1.1920928955078125e-05
halmd/test/unit/observables/ssf.cpp(192): error in "ssf_gpu_3d": absolute value of fabs(result[i][0] - get<1>(ssf_ref[i])) / npart{1} exceeds 1.1920928955078125e-05
halmd/test/unit/observables/ssf.cpp(192): error in "ssf_gpu_3d": absolute value of fabs(result[i][0] - get<1>(ssf_ref[i])) / npart{0.75} exceeds 1.1920928955078125e-05
halmd/test/unit/observables/ssf.cpp(200): error in "ssf_gpu_3d": absolute value of fabs(result[i][1] - S_q_err) / max(S_q_err, 1.){1} exceeds 1.1920928955078125e-05
halmd/test/unit/observables/ssf.cpp(206): error in "ssf_gpu_3d": check result[i][2] == count failed
Leaving test case "ssf_gpu_3d"; testing time: 12960ms