C++11: fix ambiguous assignment of boost::assign::list_of to std::vector
Use std::vector::push_back to assign values.

With C++11, we would use assignment by initializer list { }.

Building CXX object test/unit/observables/CMakeFiles/test_unit_observables_phase_space.dir/phase_space.cpp.o
test/unit/observables/phase_space.cpp: In instantiation of ‘phase_space<modules_type>::phase_space() [with modules_type = host_modules<2, double>]’:
test/unit/observables/phase_space.cpp:231:43:   required from here
test/unit/observables/phase_space.cpp:196:5: error: call of overloaded ‘vector(boost::assign_detail::generic_list<int>&)’ is ambiguous