packages.mk: update Boost to version 1.53.0
Fix Boost warning with Clang 3.2

boost/test/test_tools.hpp:309:18: error: variable 'dummy_cond' is not needed
      and will not be emitted [-Werror,-Wunneeded-internal-declaration]
namespace { bool dummy_cond = false; }
                 ^
1 error generated.

The update follows git://git.colberg.org/packages.git, which is maintained by
Peter Colberg.