test/…/power_law: fix denormalised float values
The GPU test occasionally failed due to an infinite potential energy
evaluated in single floating-point precision at the host for reference.
We reduce the cutoff (box size) such that the energy shift does not fall
below 1.18e-38.

[24-02-2014 02:59:46.619879] interaction strength ε = [2,2]((1,0.5),(0.5,0.25))
[24-02-2014 02:59:46.619916] interaction range σ = [2,2]((1,2),(2,4))
[24-02-2014 02:59:46.619937] power law index: n = [2,2]((6,12),(12,24))
[24-02-2014 02:59:46.619951] cutoff length r_c = [2,2]((50,50),(50,50))
[24-02-2014 02:59:46.619970] cutoff energy U = [2,2]((6.4e-11,2.048e-21),(2.048e-21,-1.32914e+179))
.../test/unit/mdsim/potentials/power_law.cpp(243): error in "power_law_gpu": difference{3.40282e+38} between en_pot_{inf} and en_pot[i]{6.04613062e-28} exceeds 1.43051147e-05

http://my.cdash.org/testDetails.php?test=13915152&build=574215