Fix build error with Clang
/.../src/halmd/mdsim/gpu/binning.hpp:63:42: error: no matching function for call to 'make_shared'
      , std::shared_ptr<logger> logger = std::make_shared<logger>()
                                         ^~~~~~~~~~~~~~~~~~~~~~~~

For similar errors see http://my.cdash.org/viewBuildError.php?buildid=542151

The issue is resolved by prefixing the typename "logger" with its
namespace scope:

find halmd/ -type f | xargs sed -e '/logger =/s/<logger>/<halmd::logger>/g' -i

This regression was introduced in commit:3fea73c.