readers/h5md: fix unused variable warning with Clang
Use C++11 lambda instead of Boost.Lambda, if compiling with C++11.

boost/lambda/core.hpp:71:37: error: unused variable '_3' [-Werror,-Wunused-variable]
  boost::lambda::placeholder3_type& _3 = free3;
                                    ^