cmake: upgrade minimum required Boost version to 1.49.0
HALMD fails to compile against Boost ≤ 1.47 with errors

error: use of deleted function …

Instead of setting the minimum required version to 1.48.0, require
Boost 1.49.0 for proper support of GCC 4.7, see commit:5b10115.