utility/tuple: fix assignment to tuple of references from tuple of references
This allows assignment of tie(...) = tie(...), which is supported by Boost.Tuple and C++11.

halmd/utility/tuple.hpp(170): error: implicitly generated assignment operator cannot copy:
reference member "halmd::tuple<T0, T1, void>::t0 [with T0=halmd::detail::numeric::blas::fixed_vector<float, 3UL> &, T1=int &]"
reference member "halmd::tuple<T0, T1, void>::t1 [with T0=halmd::detail::numeric::blas::fixed_vector<float, 3UL> &, T1=int &]"