gpu::forces::lj_kernel: fix FTBFS due to missing texture definition.
The param texture has to be both declared and *defined* [1], however textures
as static members are not supported with CUDA 3.1 [2], therefore we move it to
namespace scope.

[1] /tmp/tmpxft_00004bbf_00000000-1_lj_kernel.cudafe1.stub.c:34: undefined reference to `halmd::mdsim::gpu::forces::lj_kernel::lj_potential::param'

[2] halmd/mdsim/gpu/forces/lj_kernel.cu:55: error: ‘static’ may not be used when defining (as opposed to declaring) a static data member