writers/h5md: fix FTBFS with GCC and -std=c++98
If T is a const or non-const reference, “T data = slot()” will result in
a reference. If T is not a reference, “T data = slot()” will result in a
copy, which is fine since the slot returns by value anyway.

halmd/io/writers/h5md/append.cpp: In instantiation of ‘void halmd::io::writers::h5md::write_dataset(H5::DataSet&, const H5::Group&, const string&, const boost::function<R()>&) [with T = float&; std::string = std::basic_string<char>]’:
halmd/io/writers/h5md/append.cpp:115:91:   required from ‘halmd::connection halmd::io::writers::h5md::append::on_write(halmd::io::writers::h5md::append::subgroup_type&, const boost::function<R()>&, const std::vector<std::basic_string<char> >&) [with T = float&; halmd::io::writers::h5md::append::subgroup_type = H5::Group]’
halmd/io/writers/h5md/append.cpp:171:87:   required from here
halmd/io/writers/h5md/append.cpp:95:14: error: forming reference to reference type ‘float&’