demangle: fix unused variable warning with Clang
Remove unused code to print std::vector<std::string>.

boost/lambda/core.hpp:70:37: error: unused variable '_2' [-Werror,-Wunused-variable]
  boost::lambda::placeholder2_type& _2 = free2;
                                    ^
boost/lambda/core.hpp:71:37: error: unused variable '_3' [-Werror,-Wunused-variable]
  boost::lambda::placeholder3_type& _3 = free3;