packages.mk: patch Boost.Log to fix compilation with C++11
http://sourceforge.net/projects/boost-log/forums/forum/710022/topic/5221848

Boost.Log revision 667 resolves an issue with regard to conversion of
std::basic_string<char> to boost::log_mt_posix::basic_slim_string<char>.

[  2%] Building CXX object halmd/io/CMakeFiles/halmd_io.dir/logger.cpp.o
In file included from boost/log/sources/severity_logger.hpp:27:0,
                 from halmd/io/logger.hpp:29,
                 from halmd/io/logger.cpp:35:
boost/log/sources/basic_logger.hpp: In instantiation of ‘std::pair<typename boost::log_mt_posix::basic_attribute_set<CharT>::iterator, bool> boost::log_mt_posix::sources::basic_logger<CharT, FinalT, ThreadingModelT>::add_attribute_unlocked(const string_type&, const boost::shared_ptr<boost::log_mt_posix::attribute>&) [with CharT = char; FinalT = boost::log_mt_posix::sources::severity_logger<halmd::logging::severity_level>; ThreadingModelT = boost::log_mt_posix::sources::single_thread_model; typename boost::log_mt_posix::basic_attribute_set<CharT>::iterator = boost::log_mt_posix::basic_attribute_set<char>::iter<false>; boost::log_mt_posix::sources::basic_logger<CharT, FinalT, ThreadingModelT>::string_type = std::basic_string<char>]’:
boost/log/sources/basic_logger.hpp:556:60:   required from ‘std::pair<typename boost::mpl::reverse_fold<FeaturesT, boost::log_mt_posix::sources::basic_logger<CharT, FinalT, boost::log_mt_posix::sources::single_thread_model>, boost::log_mt_posix::sources::aux::inherit_logger_features>::type::attribute_set_type::iterator, bool> boost::log_mt_posix::sources::basic_composite_logger<CharT, FinalT, boost::log_mt_posix::sources::single_thread_model, FeaturesT>::add_attribute(const string_type&, const boost::shared_ptr<boost::log_mt_posix::attribute>&) [with CharT = char; FinalT = boost::log_mt_posix::sources::severity_logger<halmd::logging::severity_level>; FeaturesT = boost::mpl::vector1<boost::log_mt_posix::sources::severity<halmd::logging::severity_level> >; typename boost::mpl::reverse_fold<FeaturesT, boost::log_mt_posix::sources::basic_logger<CharT, FinalT, boost::log_mt_posix::sources::single_thread_model>, boost::log_mt_posix::sources::aux::inherit_logger_features>::type::attribute_set_type::iterator = boost::log_mt_posix::basic_attribute_set<char>::iter<false>; boost::log_mt_posix::sources::basic_composite_logger<CharT, FinalT, boost::log_mt_posix::sources::single_thread_model, FeaturesT>::string_type = std::basic_string<char>]’
halmd/io/logger.cpp:166:5:   required from ‘void halmd::wrap_add_attribute(halmd::logger&, const string&, const T&) [with T = std::basic_string<char>; halmd::logger = boost::log_mt_posix::sources::severity_logger<halmd::logging::severity_level>; std::string = std::basic_string<char>]’
halmd/io/logger.cpp:181:66:   required from here
boost/log/sources/basic_logger.hpp:227:62: error: no matching function for call to ‘boost::log_mt_posix::basic_attribute_set<char>::insert(std::pair<std::basic_string<char>, boost::shared_ptr<boost::log_mt_posix::attribute> >)’
boost/log/sources/basic_logger.hpp:227:62: note: candidates are:
In file included from boost/log/attributes/attribute_values_view.hpp:32:0,
                 from boost/log/filters/basic_filters.hpp:32,
                 from boost/log/filters/attr.hpp:38,
                 from halmd/io/logger.cpp:24:
boost/log/attributes/attribute_set.hpp:496:50: note: std::pair<boost::log_mt_posix::basic_attribute_set<CharT>::iter<false>, bool> boost::log_mt_posix::basic_attribute_set<CharT>::insert(const key_type&, const mapped_type&) [with CharT = char; boost::log_mt_posix::basic_attribute_set<CharT>::key_type = boost::log_mt_posix::basic_slim_string<char>; boost::log_mt_posix::basic_attribute_set<CharT>::mapped_type = boost::shared_ptr<boost::log_mt_posix::attribute>]
boost/log/attributes/attribute_set.hpp:496:50: note:   candidate expects 2 arguments, 1 provided
boost/log/attributes/attribute_set.hpp:505:33: note: std::pair<boost::log_mt_posix::basic_attribute_set<CharT>::iter<false>, bool> boost::log_mt_posix::basic_attribute_set<CharT>::insert(boost::log_mt_posix::basic_attribute_set<CharT>::const_reference) [with CharT = char; boost::log_mt_posix::basic_attribute_set<CharT>::const_reference = const std::pair<const boost::log_mt_posix::basic_slim_string<char>, boost::shared_ptr<boost::log_mt_posix::attribute> >&]
boost/log/attributes/attribute_set.hpp:505:33: note:   no known conversion for argument 1 from ‘std::pair<std::basic_string<char>, boost::shared_ptr<boost::log_mt_posix::attribute> >’ to ‘boost::log_mt_posix::basic_attribute_set<char>::const_reference {aka const std::pair<const boost::log_mt_posix::basic_slim_string<char>, boost::shared_ptr<boost::log_mt_posix::attribute> >&}’
boost/log/attributes/attribute_set.hpp:517:10: note: template<class FwdIteratorT> void boost::log_mt_posix::basic_attribute_set::insert(FwdIteratorT, FwdIteratorT) [with FwdIteratorT = FwdIteratorT; CharT = char]
boost/log/attributes/attribute_set.hpp:517:10: note:   template argument deduction/substitution failed: