integrators/brownian: fix building unit test
Test case names need to be different if both single and double-single
precision are enabled for the GPU backend.

In file included from /usr/include/boost/test/unit_test.hpp:19,
                 from test/unit/mdsim/integrators/brownian.cpp:26:
test/unit/mdsim/integrators/brownian.cpp:488:25: error: redefinition of 'struct brownian_free_gpu_2d'
  488 | BOOST_FIXTURE_TEST_CASE(brownian_free_gpu_2d, set_cuda_device) {
      |                         ^~~~~~~~~~~~~~~~~~~~