predicates/greater: fix FTBFS with GCC and -std=c++98
boost::make_shared passes by const&, so we need not specify const& for template parameters.

http://www.boost.org/doc/libs/release/libs/smart_ptr/make_shared.html#functions

halmd/utility/predicates/greater.cpp: In instantiation of ‘static void halmd::predicates::greater<value_type>::luaopen(lua_State*, const char*) [with value_type = double; lua_State = lua_State]’:
halmd/utility/predicates/greater.cpp:63:22:   required from here
halmd/utility/predicates/greater.cpp:43:5: error: no matching function for call to ‘def(const char [8], <unresolved overloaded function type>)’
halmd/utility/predicates/greater.cpp:43:5: note: candidates are:
In file included from luabind/class.hpp:94:0,
                 from luabind/luabind.hpp:28,
                 from halmd/utility/lua/lua.hpp:26,
                 from halmd/utility/predicates/greater.cpp:24:
luabind/function.hpp:47:7: note: template<class F, class Policies> luabind::scope luabind::def(const char*, F, const Policies&)
luabind/function.hpp:47:7: note:   template argument deduction/substitution failed:
halmd/utility/predicates/greater.cpp:43:5: note:   could not resolve address from overloaded function ‘& make_shared<halmd::predicates::greater<double>, const function_type&, double>’
In file included from luabind/class.hpp:94:0,
                 from luabind/luabind.hpp:28,
                 from halmd/utility/lua/lua.hpp:26,
                 from halmd/utility/predicates/greater.cpp:24:
luabind/function.hpp:54:7: note: template<class F> luabind::scope luabind::def(const char*, F)
luabind/function.hpp:54:7: note:   template argument deduction/substitution failed:
halmd/utility/predicates/greater.cpp:43:5: note:   could not resolve address from overloaded function ‘& make_shared<halmd::predicates::greater<double>, const function_type&, double>’