cmake: fix linking of halmd binary with newer GNU ld.
With newer version of GNU ld, indirect linking through intermediate
libraries does not work anymore, so we have to explicitly link halmd
against common libraries.

Linking CXX executable halmd
/usr/bin/ld: CMakeFiles/halmd.dir/main.cpp.o: undefined reference to symbol 'boost::log2_mt_posix::aux::stream_provider<char>::allocate_compound(boost::log2_mt_posix::basic_record<char> const&)'
/usr/bin/ld: note: 'boost::log2_mt_posix::aux::stream_provider<char>::allocate_compound(boost::log2_mt_posix::basic_record<char> const&)' is defined in DSO /opt/boost_1_46_1/lib/libboost_log.so.1.46.1 so try adding it to the linker command line
/opt/boost_1_46_1/lib/libboost_log.so.1.46.1: could not read symbols: Invalid operation
collect2: ld returned 1 exit status