test: use HALMD_TEST_INIT instead of init_unit_test() in multi_range unit test
The signature of the unit test initialisation function varies between the
static and the dynamic boost_unit_test_framework library, which makes it
impractical (though not impossible) to use for manual initialisation of
the master test suite.

test/unit/algorithm/multi_range.cpp:436:72: error: invalid conversion from ‘bool (*)()’ to ‘boost::unit_test::init_unit_test_func {aka boost::unit_test::test_suite* (*)(int, char**)}’ [-fpermissive]