Revert "packages.mk: update Luabind to commit 0.9.1-27-g62f1857"
The ununsed variable fix works with GCC 4.7, but fails to compile with GCC 4.4.

luabind/operator.hpp:347: error: uninitialized const ‘luabind::<unnamed>::self’
luabind/operator.hpp:348: error: uninitialized const ‘luabind::<unnamed>::const_self’

This reverts commit f7f80648e997bc978c72630bd0aba5d7c1dd0e3c.