signal: fix FTBFS with Boost 1.50.0 due to ambiguous namespace
This is a good example why “using namespace” is evil.

test/unit/utility/signal.cpp:201:20: error: reference to 'function_traits' is ambiguous
    size_t count = function_traits<typename signal_type::slot_function_type>::arity + 1;
                   ^
test/unit/utility/signal.cpp:190:8: note: candidate found by name lookup is 'function_traits'
struct function_traits;
       ^
boost/type_traits/function_traits.hpp:168:8: note: candidate found by name lookup is 'boost::function_traits'
struct function_traits :
       ^