test: fix truncation from floating-point to integer for box ratios
As of this commit, HALMD compiles without warnings with Clang (3.1).

Besides non-critical warnings fixed in previous commits, Clang uncovered
a critical error with regard to use of boost::assign::list_of in tests.

The type of a list_of expression is determined by the *first element*.

In this case, a box ratio was truncated from double to integer.

test/unit/mdsim/integrators/verlet.cpp:147:51: error: implicit conversion turns literal floating-point number into
      integer: 'double' to 'const Ty' (aka 'const int') [-Werror,-Wliteral-conversion]
    box_ratios = (dimension == 3) ? list_of(1)(2)(1.01) : list_of(1)(2);
                                    ~~~~~~~       ^~~~

test/unit/observables/thermodynamics.cpp:307:51: error: implicit conversion turns literal floating-point number
      into integer: 'double' to 'const Ty' (aka 'const int') [-Werror,-Wliteral-conversion]
    box_ratios = (dimension == 3) ? list_of(1)(2)(1.01) : list_of(1)(2);
                                    ~~~~~~~       ^~~~

This kind of mistake will be a thing of the past with C++11 initializer lists.