mdsim/gpu/particle.cpp: fix FTBFS due to missing swap() function
cuda::memory::*::vector does not provide a swap() _member_ function. On the
other hand, dsfloat_cuda_vector does not have a _free_ swap function. As
solution, we add a free swap function to dsfloat_cuda_vector. An effective way
is by defining a friend function inside of the class.

The following error appeared in most configurations of the nightly tests:

.../halmd/mdsim/gpu/particle.cpp: In instantiation of ‘void halmd::mdsim::gpu::particle<dimension, float_type_>::rearrange(const cuda::memory::device::vector<unsigned int>&) [with int dimension = 3; float_type_ = float]’:
halmd/mdsim/gpu/particle.cpp:358:16:   required from here
halmd/mdsim/gpu/particle.cpp:206:5: error: ‘halmd::mdsim::gpu::particle<3, float>::position_array_type’ has no member named ‘swap’

     position.swap(*g_position);
     ^