lua_wrapper: fix FTBFS due to wrong header order.
/home/pcolberg/usr/rhel5-x86_64/luabind-0.9/include/luabind/get_main_thread.hpp:12: error: expected constructor, destructor, or type conversion before ‘*’ token
/home/pcolberg/usr/rhel5-x86_64/luabind-0.9/include/luabind/shared_ptr_converter.hpp: In constructor ‘luabind::detail::shared_ptr_deleter::shared_ptr_deleter(lua_State*, int)’:
/home/pcolberg/usr/rhel5-x86_64/luabind-0.9/include/luabind/shared_ptr_converter.hpp:21: error: ‘get_main_thread’ was not declared in this scope
/home/pcolberg/usr/rhel5-x86_64/luabind-0.9/include/luabind/detail/constructor.hpp: In function ‘void luabind::detail::inject_backref(lua_State*, T*, luabind::wrap_base*)’:
/home/pcolberg/usr/rhel5-x86_64/luabind-0.9/include/luabind/detail/constructor.hpp:28: error: there are no arguments to ‘get_main_thread’ that depend on a template parameter, so a declaration of ‘get_main_thread’ must be available
/home/pcolberg/usr/rhel5-x86_64/luabind-0.9/include/luabind/detail/constructor.hpp:28: error: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)