Fix FTBFS error when compiling with single precision
Compilation with HALMD_VARIANT_GPU_SINGLE_PRECISION=ON resulted in the below
error messages. The reason is that names of test cases cannot be identifiers
such as "float". (dsfloat is hidden in the halmd namespace.) As solution,
prefix these names with "type_" as in the raw_array unit test.

.../test/unit/mdsim/particle.cpp:798:32: error: expected identifier or '{'
        BOOST_AUTO_TEST_SUITE( float )
                               ^
.../test/unit/mdsim/particle.cpp:798:9: error: expected unqualified-id
        BOOST_AUTO_TEST_SUITE( float )
        ^
.../include/boost/test/unit_test_suite.hpp:72:9: note: expanded from macro 'BOOST_AUTO_TEST_SUITE'
        BOOST_AUTO_TEST_SUITE_NO_DECOR,                                 \