CMakeLists: fix issues with static linkage of Boost libraries
Store HALMD_USE_STATIC_LIBS as cache variable. Otherwise, subsequent
CMake calls would fall back to dynamic linkage.

The Boost.Log library depends on Boost.Filesystem and must be mentioned
first on the command line. The wrong order causes many linker errors:
"undefined reference to `boost::filesystem::something`".