host/random: fix FTBFS with Clang C++ compiler.
halmd/random/host/random.hpp:113:12: error: use of undeclared identifier 'make_pair'
    return make_pair(x, y);
           ^

HALMD now builds with Clang, requires Luabind v0.9.1-15-g3044a90 or later.

clang version 2.9 (trunk 120863)
Target: x86_64-unknown-linux-gnu
Thread model: posix