cuda_wrapper: fix FTBFS with CUDA 3.2.
The API changes in CUDA 3.2 are not documented in the release notes.

cuda_wrapper/driver/mem.hpp: In function ‘unsigned int cuda::driver::mem::total()’:
cuda_wrapper/driver/mem.hpp:39: error: cannot convert ‘unsigned int*’ to ‘size_t*’ for argument ‘1’ to ‘CUresult cuMemGetInfo_v2(size_t*, size_t*)’
cuda_wrapper/driver/mem.hpp: In function ‘unsigned int cuda::driver::mem::used()’:
cuda_wrapper/driver/mem.hpp:49: error: cannot convert ‘unsigned int*’ to ‘size_t*’ for argument ‘1’ to ‘CUresult cuMemGetInfo_v2(size_t*, size_t*)’
cuda_wrapper/driver/mem.hpp: In function ‘unsigned int cuda::driver::mem::free()’:
cuda_wrapper/driver/mem.hpp:59: error: cannot convert ‘unsigned int*’ to ‘size_t*’ for argument ‘1’ to ‘CUresult cuMemGetInfo_v2(size_t*, size_t*)’