test of euler integrate: increase tolerance
The test unit/mdsim/integrators/euler/gpu/dsfloat/3d/linear fails
occasionally, reported in bug #702686. See also, e.g.,
http://my.cdash.org/testDetails.php?test=34702535&build=1285576

A likely reason for this are ad-hoc tolerances, which do not take the magnitude
of the initial velocities into account. Since velocities are drawn randomly,
some outliers may produce larger errors. (And even larger since rescaling was
removed from the velocity/boltzmann module.) So let's increase the tolerance by
a factor of 2.5, which should "solve" the "problem".

Test failures could be reproduces with the following RNG seeds on GTX 960 hardware:
1598678060 2296142685 470596107 3090987962

[11-10-2017 11:39:17.898002] random (GPU): set RNG seed: 1598678060
[11-10-2017 11:39:17.899363] temperature of Boltzmann distribution: 1
position particles on lattice
[11-10-2017 11:39:17.899413] placing particles on fcc lattice: a = 156.969
[11-10-2017 11:39:17.899424] [WARNING] lattice not fully occupied (4096 sites)
set particle velocities
running Euler integration for linear motion over 1000000 steps
/home/mi/hoefling/projects/gpgpu/halmd/test/unit/mdsim/integrators/euler.cpp(153): error: in "euler_gpu_dsfloat_3d_linear": absolute value of norm_inf(r_final - r_analytic){0.0009765625} exceeds 0.000571048586
Maximum deviation: 0.000976562, tolerance: 0.000571049
/home/mi/hoefling/projects/gpgpu/halmd/test/unit/mdsim/integrators/euler.cpp(157): error: in "euler_gpu_dsfloat_3d_linear": check max_deviation < tolerance has failed [0.0009765625 >= 0.000571048586]