Fixes CUDA error with new Boost versions
nvcc has an bug when compiling new Boost versions (>= 1.69.0):
`boost/core/noncopyable.hpp(42): error: defaulted default constructor cannot be constexpr because the corresponding implicitly declared default constructor would not be constexpr`

I could track down the error to the include of boost/function.hpp in halmd/algorithm/gpu/copy_if_kernel.hpp.

This fix defines BOOST_NO_CXX11_CONSTEXPR around the include of boost/function.hpp,
only if nvcc is used and depending on the Boost version (>= 1.69.0).