test/numeric/pow: fix missing -lrt with statically linked Boost library.
Linking CXX executable test_pow
CMakeFiles/test_pow.dir/pow.cpp.o: In function `performance::test_method()':
pow.cpp:(.text+0x897): undefined reference to `clock_gettime'
pow.cpp:(.text+0x93e): undefined reference to `clock_gettime'
pow.cpp:(.text+0xae9): undefined reference to `clock_gettime'
pow.cpp:(.text+0xb86): undefined reference to `clock_gettime'
pow.cpp:(.text+0xd30): undefined reference to `clock_gettime'