test/…/phase_space: fix incomplete comparison of particle positions
Due to use of the wrong loop counter for the comparison of particle
positions between input and result samples, only the i-th position
of the i-th type was validated.

Note that the unit/observables/phase_space/host/* tests now fail
due to too strict tolerances for the position comparison.

9: Test command: /home/pcolberg/research/projects/halmd/build/debug/test/unit/observables/test_unit_observables_phase_space "--run_test=phase_space_host_2d" "--log_level=test_suite"
9: Test timeout computed to be: 9.99988e+06
9: Avoid ctest truncation of output: CTEST_FULL_OUTPUT
9: HALMD 0.1-2227-g9753aef (master)
9: Running 1 test case...
9: Entering test suite "phase_space"
9: Entering test case "phase_space_host_2d"
9: initialise simulation modules
9: [24-11-2011 15:47:02.990752] number of particles: 1567
9: [24-11-2011 15:47:02.991038] number of particle types: 4
9: [24-11-2011 15:47:02.991076] number of particles per type: 1024 512 30 1
9: [24-11-2011 15:47:02.991189] total number of particles: 1567
9: [24-11-2011 15:47:02.991217] number density: 8.81437
9: [24-11-2011 15:47:02.991256] edge lengths of simulation box: 13.3333 13.3333
9: [24-11-2011 15:47:02.991340] simulation time-step: 0
9: [24-11-2011 15:47:02.991433] set particle positions from phase space sample
9: [24-11-2011 15:47:02.991958] set particle velocities from phase space sample
9: /theory2/u4/pcolberg/research/projects/halmd/test/unit/observables/phase_space.cpp(178): error in "phase_space_host_2d": absolute value of norm_inf(result_position[j] - input_position[j]){2.8421709430404007e-14} exceeds 2.8421709430404007e-14
9: /theory2/u4/pcolberg/research/projects/halmd/test/unit/observables/phase_space.cpp(178): error in "phase_space_host_2d": absolute value of norm_inf(result_position[j] - input_position[j]){5.6843418860808015e-14} exceeds 5.1958437552457326e-14
9: /theory2/u4/pcolberg/research/projects/halmd/test/unit/observables/phase_space.cpp(178): error in "phase_space_host_2d": absolute value of norm_inf(result_position[j] - input_position[j]){5.6843418860808015e-14} exceeds 5.2180482157382357e-14
9: /theory2/u4/pcolberg/research/projects/halmd/test/unit/observables/phase_space.cpp(178): error in "phase_space_host_2d": absolute value of norm_inf(result_position[j] - input_position[j]){5.6843418860808015e-14} exceeds 5.2402526762307389e-14
9: /theory2/u4/pcolberg/research/projects/halmd/test/unit/observables/phase_space.cpp(178): error in "phase_space_host_2d": absolute value of norm_inf(result_position[j] - input_position[j]){5.6843418860808015e-14} exceeds 5.262457136723242e-14
9: /theory2/u4/pcolberg/research/projects/halmd/test/unit/observables/phase_space.cpp(178): error in "phase_space_host_2d": absolute value of norm_inf(result_position[j] - input_position[j]){5.6843418860808015e-14} exceeds 5.2846615972157451e-14
9: /theory2/u4/pcolberg/research/projects/halmd/test/unit/observables/phase_space.cpp(178): error in "phase_space_host_2d": absolute value of norm_inf(result_position[j] - input_position[j]){5.6843418860808015e-14} exceeds 5.3068660577082483e-14
9: /theory2/u4/pcolberg/research/projects/halmd/test/unit/observables/phase_space.cpp(178): error in "phase_space_host_2d": absolute value of norm_inf(result_position[j] - input_position[j]){5.6843418860808015e-14} exceeds 5.3290705182007514e-14
9: /theory2/u4/pcolberg/research/projects/halmd/test/unit/observables/phase_space.cpp(178): error in "phase_space_host_2d": absolute value of norm_inf(result_position[j] - input_position[j]){5.6843418860808015e-14} exceeds 5.3512749786932545e-14
9: /theory2/u4/pcolberg/research/projects/halmd/test/unit/observables/phase_space.cpp(178): error in "phase_space_host_2d": absolute value of norm_inf(result_position[j] - input_position[j]){5.6843418860808015e-14} exceeds 5.3734794391857577e-14
9: /theory2/u4/pcolberg/research/projects/halmd/test/unit/observables/phase_space.cpp(178): error in "phase_space_host_2d": absolute value of norm_inf(result_position[j] - input_position[j]){5.6843418860808015e-14} exceeds 5.3956838996782608e-14
9: /theory2/u4/pcolberg/research/projects/halmd/test/unit/observables/phase_space.cpp(178): error in "phase_space_host_2d": absolute value of norm_inf(result_position[j] - input_position[j]){5.6843418860808015e-14} exceeds 5.4178883601707639e-14
9: /theory2/u4/pcolberg/research/projects/halmd/test/unit/observables/phase_space.cpp(178): error in "phase_space_host_2d": absolute value of norm_inf(result_position[j] - input_position[j]){5.6843418860808015e-14} exceeds 5.440092820663267e-14
…