test: adapt lattice offset in lattice unit test
test/unit/mdsim/positions/lattice.cpp(186): error in "lattice_host_3d": absolute value of norm_1(r_cm + offset / 4) / norm_1(corner){0.125} exceeds 2.384185791015625e-07
test/unit/mdsim/positions/lattice.cpp(187): error in "lattice_host_3d": absolute value of norm_1(r_min + corner) / norm_1(corner){0.125} exceeds 1.1920928955078125e-07
test/unit/mdsim/positions/lattice.cpp(188): error in "lattice_host_3d": absolute value of norm_1(r_max - corner + offset / 2) / norm_1(corner){0.125} exceeds 1.1920928955078125e-07

Since commit 91f850d, the close-packed lattice primitives generate
unit lattice vectors at origin [0.25, 0.25] or [0.25, 0.25, 0.25],
which ensures that spheres placed at the lattice points will not
exceed the boundaries of the simulation domain. This will matter
once walls are supported, besides periodic boundaries.