fix FTBFS with CUDA 5.5
The reduction functors defined in observables/gpu/thermodynamics_kernel.hpp were lacking the __device__ keyword for operator()() if compiled by NVCC. The __device__ keyword was further missing in the definitions in the *.cu file.

.../halmd/observables/gpu/thermodynamics_kernel.hpp(76): error: calling a __device__ function("operator*") from a __host__ function("operator()") is not allowed
          detected during instantiation of "double halmd::observables::gpu::kinetic_energy<dimension, float_type>::operator()() const [with dimension=3, float_type=halmd::detail::numeric::mp::dsfloat]"
.../halmd/observables/gpu/thermodynamics_kernel.cu(145): here

.../halmd/observables/gpu/thermodynamics_kernel.cu(44): warning: a __device__ function("halmd::observables::gpu::kinetic_energy<dimension, float_type>::operator()") redeclared without __device__, hence treated as a __host__ __device__ function

http://my.cdash.org/viewBuildError.php?buildid=509927

This fixes #207320.