posix_signal: fix FTBFS with Boost 1.51.0 with GCC 4.7
Switch from boost::unordered_map to std::unordered_map (C++11).

In file included from boost/unordered/unordered_map.hpp:17:0,
                 from boost/unordered_map.hpp:16,
                 from halmd/utility/posix_signal.hpp:23,
                 from test/unit/utility/posix_signal.cpp:29:
boost/unordered/detail/equivalent.hpp: In copy constructor ‘boost::unordered::detail::grouped_node<A, T>::grouped_node(const boost::unordered::detail::grouped_node<A, T>&)’:
boost/unordered/detail/equivalent.hpp:54:25: error: there are no arguments to ‘assert’ that depend on a template parameter, so a declaration of ‘assert’ must be available [-fpermissive]
boost/unordered/detail/equivalent.hpp:54:25: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
boost/unordered/detail/equivalent.hpp: In copy constructor ‘boost::unordered::detail::grouped_ptr_node<T>::grouped_ptr_node(const boost::unordered::detail::grouped_ptr_node<T>&)’:
boost/unordered/detail/equivalent.hpp:101:25: error: there are no arguments to ‘assert’ that depend on a template parameter, so a declaration of ‘assert’ must be available [-fpermissive]