test: check dependency injection of C++ modules from Lua.
Modules are successively instantiated in Lua using shared pointers,
where dependencies of a module are passed to its constructor as
arguments. For dependencies which are derived classes, we check that
Luabind down- and up-casts to the type of the constructor argument.

This commit *passes* the test if compiled with GCC 4.1 and 4.2.

This commit *fails* the test if compiled with GCC 4.3 and 4.4.

Test failures with enabled CUDA support:

dependency_injection.cpp(291): error in "statically_registered_gpu_modules": [string "device = assert2(halmd_wrapper.utility.gpu...."]:1: attempt to index global 'halmd_wrapper' (a nil value)
dependency_injection.cpp(294): error in "statically_registered_gpu_modules": [string "particle = assert2(halmd_wrapper.mdsim.gpu...."]:1: attempt to index global 'halmd_wrapper' (a nil value)
dependency_injection.cpp(297): error in "statically_registered_gpu_modules": [string "box = assert2(halmd_wrapper.mdsim.box_3_(pa..."]:1: attempt to index global 'halmd_wrapper' (a nil value)
dependency_injection.cpp(300): error in "statically_registered_gpu_modules": [string "integrator = assert2(halmd_wrapper.mdsim.gp..."]:1: attempt to index global 'halmd_wrapper' (a nil value)

Test failures with disabled CUDA support:

dependency_injection.cpp(268): error in "statically_registered_host_modules": No matching overload found, candidates:
void __init(luabind::argument const&,custom [N5boost10shared_ptrIN5halmd5mdsim4host8particleILj3EdEEEE],custom [N5boost10shared_ptrIN5halmd5mdsim3boxILi3EEEEE],custom [d])