fix broken test unit/observables/thermodynamics/*
.../test/unit/observables/thermodynamics.cpp(190): error in
"lennard_jones_fluid_gpu_2d": absolute value of
norm_inf(thermodynamics->v_cm()){0.030281608706194674} exceeds
1.1920928955078126e-08

As caching has been added to the thermodynamics module, the mean velocity must
be re-evaluated after shifting the velocities. Advancing the simulation clock
invalidates the caches and fixes the test suite.