CUDA 3.0: work around compiler error with enum in namespace.
Apparently the CUDA 3.0 compiler does not support enumeration types
as template parameters if these are declared in a namespace.

    /tmp/tmpxft_00000245_00000000-1_ljfluid_nbr.cudafe1.stub.c:6: error: '_ZN5halmd5C0POTE' was not declared in this scope
    /tmp/tmpxft_00000245_00000000-1_ljfluid_nbr.cudafe1.stub.c:6: error: template-id '__wrapper__device_stub_sample_potential<<expression error> >' for 'void halmd::cu::ljfluid::__wrapper__device_stub_sample_potential(float3*&, const float2&)' does not match any template declaration
    /tmp/tmpxft_00000245_00000000-1_ljfluid_nbr.cudafe1.stub.c:6: error: invalid function declaration
    /tmp/tmpxft_00000245_00000000-1_ljfluid_nbr.cudafe1.stub.c:12: error: '_ZN5halmd5C2POTE' was not declared in this scope
    /tmp/tmpxft_00000245_00000000-1_ljfluid_nbr.cudafe1.stub.c:12: error: template-id '__wrapper__device_stub_sample_potential<<expression error> >' for 'void halmd::cu::ljfluid::__wrapper__device_stub_sample_potential(float3*&, const float2&)' does not match any template declaration
    /tmp/tmpxft_00000245_00000000-1_ljfluid_nbr.cudafe1.stub.c:12: error: invalid function declaration
    /tmp/tmpxft_00000245_00000000-1_ljfluid_nbr.cudafe1.stub.c:6: error: '_ZN5halmd5UNARYE' was not declared in this scope
    /tmp/tmpxft_00000245_00000000-1_ljfluid_nbr.cudafe1.stub.c:6: error: '_ZN5halmd5C0POTE' was not declared in this scope
    /tmp/tmpxft_00000245_00000000-1_ljfluid_nbr.cudafe1.stub.c:6: error: template-id '__wrapper__device_stub_mdstep<halmd::cu::detail::vector<float, 3u>, <expression error>, <expression error>, float4>' for 'void halmd::cu::ljfluid::__wrapper__device_stub_mdstep(const float4*&, float4*&, float4*&, float*&, float4*&, float4*&)' does not match any template declaration