fix broken test unit/mdsim/velocities/boltzmann/*
.../test/unit/mdsim/velocities/boltzmann.cpp(119): error in "boltzmann_gpu_2d":
difference{0.555556} between thermodynamics->temp(){2.0000000008023577} and
scale * scale * temp{4.5} exceeds 0.014999999999999999

As caching has been added to the thermodynamics module, temperature was not
re-evaluated after velocity rescaling. Advancing the simulation clock
invalidates the caches and fixes the test suite.