test: fix FTBFS in lattice unit test with GCC 4.1.
std::pow requires same-type (float, float) arguments with GCC 4.1.

test/mdsim/position/lattice.cpp: In function ‘void lattice(const std::string&) [with int dimension = 2]’:
test/mdsim/position/lattice.cpp:361:   instantiated from here
test/mdsim/position/lattice.cpp:243: error: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
/usr/include/bits/mathcalls.h:154: note: candidate 1: double pow(double, double)
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../include/c++/4.1.2/cmath:345: note: candidate 2: float std::pow(float, float)
test/mdsim/position/lattice.cpp:243: error: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
/usr/include/bits/mathcalls.h:154: note: candidate 1: double pow(double, double)
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../include/c++/4.1.2/cmath:357: note: candidate 2: float std::pow(float, int)