verlet_nvt_hoover: fix unused variable warning with Clang
Use C++11 lambda instead of Boost.Lambda, if compiling with C++11.

boost/lambda/core.hpp:69:37: error: unused variable '_1' [-Werror,-Wunused-variable]
  boost::lambda::placeholder1_type& _1 = free1;
                                    ^
boost/lambda/core.hpp:70:37: error: unused variable '_2' [-Werror,-Wunused-variable]
  boost::lambda::placeholder2_type& _2 = free2;
                                    ^
boost/lambda/core.hpp:71:37: error: unused variable '_3' [-Werror,-Wunused-variable]
  boost::lambda::placeholder3_type& _3 = free3;
                                    ^